### ISSUE TITLE
"pauseWhenNoPlayers" shows last player to log off as still logged in on the server selection screen

### ISSUE THREAD

**Issue by MsWolphie** [iChun/MultiplayerServerPause#9]
I enabled the option to pause the server when no-one was on (to save the CPU cost when server was unused, and avoid useless day count inflation; it was the main reason why I installed the mod after all), but since then it still shows one online player when said player left the server, which is obviously false.

Not a game breaking bug fortunately but still weird to see myself still considered as connected to my server when I left it hours ago xD

**Comment by iChun** [comment]
Fixed for 1.2.0

**Comment by Roadhog360** [comment]
I'm still getting this issue, on Forge 1.20.1, the 1.3.0 version. Requesting reopen? @iChun 

Seems to happen if the server pauses before the last player dcs. (Which almost always happens since the disconnect button is on the pause screen) If I disconnect by doing alt+F4 then it doesn't keep my name on the list.
